[package]
name = "identity"
version = "0.1.0"
authors = ["th0rgal <thomas@starknet.id>"]
description = "Contract of the starknet identity base NFT built for compiler version 2.3.0"
repository = "https://github.com/starknet-id/identity"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = "2.3.0"

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true

[lib]
sierra = true
casm = false
