[package]
name = "identity"
version = "0.1.0"
authors = ["th0rgal <thomas@starknet.id>"]
description = "Contract of the starknet identity base NFT built for compiler version 2.3.0"
repository = "https://github.com/starknet-id/identity"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = "2.3.0"
storage_read = { git = "https://github.com/starknet-id/storage_read_component", rev = "c6c69e15d34abfc39ac51dc21b96724e2e19ff31" }
custom_uri = { git = "https://github.com/starknet-id/custom_uri_component", rev = "abb2f3d43c7be56dd5cd9f93c33af40b272c2245" }

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true

[lib]
sierra = true
casm = false
