[package]
name = "identity"
version = "0.1.0"
cairo-version = "2.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = "2.1.0"

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true
allowed-libfuncs-list.name = "experimental"
